export const talksData = [
  {
    id: 1,
    isActive: true,
    name: "Hero Alom",
    text: "Can you please send me",
    date: "02:19 pm",
  },
  {
    id: 2,
    isActive: true,
    name: "Hero Alom",
    text: "Can you please send me",
    date: "02:19 pm",
  },
  {
    id: 3,
    isActive: false,
    name: "Hero Alom",
    text: "Can you please send me",
    date: "02:19 pm",
  },
  {
    id: 4,
    isActive: false,
    name: "Hero Alom",
    text: "Can you please send me",
    date: "02:19 pm",
  },
  {
    id: 5,
    isActive: false,
    name: "Hero Alom",
    text: "Can you please send me",
    date: "02:19 pm",
  },
  {
    id: 6,
    isActive: true,
    name: "Hero Alom",
    text: "Can you please send me",
    date: "02:19 pm",
  },
  {
    id: 7,
    isActive: true,
    name: "Hero Alom",
    text: "Can you please send me",
    date: "02:19 pm",
  },
  {
    id: 8,
    isActive: false,
    name: "Hero Alom",
    text: "Can you please send me",
    date: "02:19 pm",
  },
];
